spring:
  datasource:
    url: jdbc:h2:mem:gymdb-test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

jwt:
  secret: "test-secret-change-me-please-change-me-32+"
  expirationMinutes: 5

cors:
  allowed-origins: "*"

logging:
  level:
    root: WARN
